config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :administrators
  devise_for :auth_users, controllers: { registrations: 'auth_users/registrations' }

  patch "/update_password" => "templates#update_password", as: "update_password"
  get "/auth_users/edit_password_signed" => "templates#edit_password", as: "edit_password_signed"

  get "/admin/auth_users/:id/edit_password" => "templates#edit_password_admin", as: "edit_password_admin"
  patch "/update_password_admin/:id" => "templates#update_password_admin", as: "update_password_admin"
  get "/admin/latamusers_usergroups" => "admin/latamusers_usergroups#index", as:"index_admin_usergroup"
  get "/admin/latamusers_usergroups/:id/edit" => "admin/latamusers_usergroups#edit", as:"edit_admin_usergroup", :constraints => { :id => /[^\/]+/ } 
  get "/admin/usergroups/:id" => "admin/latamusers_usergroups#show", as:"show_admin_usergroup", :constraints => { :id => /[^\/]+/ } 
  patch "/admin/latamusers_usergroups/:id" => "admin/latamusers_usergroups#update", as: "update_admin_usergroup", :constraints => { :id => /[^\/]+/ } 
  delete "/admin/usergroups/:id" => "admin/latamusers_usergroups#destroy", as: "delete_admin_usergroup", :constraints => { :id => /[^\/]+/ } 
  get "/vacio" => "templates#vacio", as: "edit_admin_administrator"

  match '/admin/administrators' => redirect('/admin/auth_users'), via: [:get]
  match '/admin/signin' =>redirect('administrators/sign_in'), via: [:get]

  # URLs para los tutoriales
  match '/static/videostv/TutorialComprimido.mp4' => redirect('https://s3-us-west-2.amazonaws.com/elpost/videostv/TutorialComprimido.mp4'), via: [:get]
  match '/static/videostv/ManulaDeUsuarioIntruduccion.mp4' => redirect('https://s3-us-west-2.amazonaws.com/elpost/videostv/ManulaDeUsuarioIntruduccion.mp4'), via: [:get]
  match '/static/videostv/manualdelprofe2.mp4' => redirect('https://s3-us-west-2.amazonaws.com/elpost/videostv/manualdelprofe2.mp4'), via: [:get]

  # Temporal para efectos de presentación
  get '/admin_statistics' => "templates#admin_statistics", as: "admin_statistics"

  Tolaria.draw_routes(self)

  get "/activities" => "templates#all", as: "activities"
  get "/activities/media" => "templates#media", as: "activities_media"
  get "/activities/reading" => "templates#reading", as: "activities_reading"
  get "/activities/vocabulary" => "templates#vocabulary", as: "activities_vocabulary"

  get "/caracterization_view/" => "templates#caracterization", as: "caracterization_profile"
  post "/caracterization_view/" => "templates#create_caracterization", as: "caracterization_profile_create"

  get "/profile" => "templates#profile", as: "profile"
  get "/articles" => "templates#articles", as: "articles"
  get "/activity/:id" => "templates#activity", as: "activity"
  get "/preview/:id" => "templates#preview", as: "preview"
  get "/generate_report" => "templates#reports", as: "reports"
  get "/phrases" => "templates#phrases", as: "phrases"
  get "/parts" => "templates#parts", as: "parts"
  get "/guided_content" => "templates#guided_content", as: "guided_content"
  get "/my_subscription" => "templates#my_subscription", as: "my_subscription"
  get "/create-group" => "templates#create_group", as: "create_group"
  get "/create-activity" => "templates#create_activity", as: "create_activity"
  get "/create-sequence" => "templates#create_sequence", as: "create_sequence"

  get "/edit-activity/:id" => "templates#edit_activity", as: "edit_activity"
  get "/edit-sequence/:id" => "templates#edit_sequence", as: "edit_sequence"

  get "/students_in_group/:code" => "templates#students_in_group", as: "students_in_group", :constraints => { :code => /[^\/]+/ }
  get "/student_activities/:id" => "templates#student_activities", as: "student_activities"
  get "/students_assignation" => "templates#students_assignation", as: "students_assignation"

  get "/students_with_activity/:id" => "templates#students_with_activity", as: "students_with_activity"
  get "/students_with_sequence/:id" => "templates#students_with_sequence", as: "students_with_sequence"

  get "/all_assigned_activities" => "templates#all_assigned_activities", as: "all_assigned_activities"
  get "/elearning" => "templates#elearning", as: "elearning"
  get "/activities_active" => "templates#activities_active", as: "activities_active"
  get "/sequences_active" => "templates#sequences_active", as: "sequences_active"

  get "/current_groups" => "templates#current_groups", as: "current_groups"
  get "/current_groups_by_id/:id" => "templates#current_groups_by_id", as: "current_groups_by_id"
  
  get "/current_students" => "templates#current_students", as: "current_students"

  get "/current_students_in_activity/:id" => "templates#current_students_in_activity", as: "current_students_in_activity"
  get "/current_students_in_sequence/:id" => "templates#current_students_in_sequence", as: "current_students_in_sequence"
  get "/preview_sequence/:id" => "templates#preview_sequence", as: "preview_sequence"

  get "/current_students_in_group/:code" => "templates#current_students_in_group", as: "current_students_in_group", :constraints => { :code => /[^\/]+/ }
  get "/current_activities_in_student/:id" => "templates#current_activities_in_student", as: "current_activities_in_student"
  get "/assigned_activities" => "templates#assigned_activities", as: "assigned_activities"
  get "/admin/auth_users/import/csv" => "templates#import", as: "import_users"
  get "/admin/media_media/utility/generate_audio" => "templates#generate_audio_layout", as: "generate_audio_layout"
  get "/about/:page" => "templates#pages", as: "pages"

  get "/open-domain-questions" => "templates#open_domain_questions", as: "open_domain_questions"
  get "/open-questions/:id" => "templates#open_questions_show", as: "open_question_show"
  get "/open-questions-api" => "templates#open_questions_api", as: "open_questions_api"

  get "/login_users_path" => "templates#view_as_user", as: "login_users_path"

  post "/get_group_students/:code" => "templates#get_students_html", as: "get_students_html", :constraints => { :code => /[^\/]+/ }
  post "/get_activities/:id_level/:id_section/:start_date/:end_date/:active/:tries" => "templates#get_activities_html", as: "get_activities_html"
  post "/create_assign_activity" => "templates#create_assign_activity", as: "create_assign_activity"
  post "/create_assign_sequence" => "templates#create_assign_sequence", as: "create_assign_sequence"
  post "/assign_activity" => "templates#assign_activity", as: "assign_activity"
  post "/assign_sequence" => "templates#assign_sequence", as: "assign_sequence"
  post "/create_student_group" => "templates#create_student_group", as: "create_student_group"

  post "/edit_activity_post" => "templates#edit_activity_post", as: "edit_activity_post"
  post "/edit_sequence_post" => "templates#edit_sequence_post", as: "edit_sequence_post"

  post "/send_contact_mail" => "templates#send_contact_mail", as: "send_contact_mail"
  post "/lesscount/:id" => "templates#lesscount", as: "lesscount"
  post "/import/auth_users" => "templates#import_users", as: "import_users_db"
  post "/generate_audio/media_media" => "templates#generate_audio", as: "generate_audio"
  post "/save_audio" => "templates#save_audio", as: "save_audio"
  post "/correct_answer" => "templates#correct_answer", as: "correct_answer"
  post "/get_words" => "templates#update_lms_words", as:"lms_words_refresh"
  post "/get_articles" => "templates#update_articles", as:"lms_articles_refresh"
  post "/get_media/:media" => "templates#update_media", as:"media_refresh"
  post "/api/userquestions/" => "templates#questions", as: "questions"
  post "/api/openquestions/" => "templates#openquestions", as: "openquestionsadd"
  post "/postActivity" => "templates#postActivity", as: "postActivity"

  post "/create_review" => "templates#open_question_create", as: "review_open_questions"

  delete "/remove_activity/:id" => "templates#remove_activity", as:"remove_activity"
  delete "/remove_secuence/:id" => "templates#remove_secuence", as:"remove_secuence"

  devise_scope :auth_user do
    authenticated :auth_user do
      root 'templates#articles', as: :authenticated_root
    end

    unauthenticated do
      root 'auth_users/sessions#new', as: :unauthenticated_root
    end
  end

  devise_scope :administrator do
    authenticated :administrator do
      root 'templates#articles', as: :authenticated_admin
    end

    unauthenticated do
      root 'auth_users/sessions#new', as: :unauthenticated_admin
    end
  end

end

app/models/lms_activity.rb
class LmsActivity < ActiveRecord::Base
    self.table_name = 'LMS_activity'

    has_many :lms_questions, :class_name => 'LmsQuestion', :foreign_key => :activity_id, dependent: :destroy
    has_many :lms_categories, through: :lms_questions, :class_name => 'LmsCategory'

    has_many :sequence_lms_activities, :class_name => 'SequenceLmsActivity', :foreign_key => :lms_activity_id, dependent: :destroy
    has_many :sequences, through: :sequence_lms_activities, :class_name => 'Sequence'

    has_many :lms_activity_vocabularies, :class_name => 'LmsActivityVocabulary', :foreign_key => :activity_id, dependent: :destroy
    has_many :lms_words, through: :lms_activity_vocabularies, :class_name => 'LmsWord'

    has_many :latamusers_useractivities, :class_name => 'LatamusersUseractivity', :foreign_key => :activity_id, dependent: :destroy
    has_many :latamusers_userquestions, through: :latamusers_useractivities, :class_name => 'LatamusersUserquestion'
    has_many :latamusers_assignedactivities, :class_name => 'LatamusersAssignedactivity', :foreign_key => :activity_id, dependent: :destroy

    has_many :activity_institutions, :class_name => 'ActivityInstitution', :foreign_key => :activity_id
    has_many :latamusers_intitutions, through: :activity_institutions, :class_name => 'LatamusersIntitution', dependent: :destroy

    belongs_to :auth_user, :class_name => 'AuthUser', :foreign_key => :created_by_id, optional: true
    belongs_to :lms_course, :class_name => 'LmsCourse', :foreign_key => :course_id, optional: true
    belongs_to :lms_level, :class_name => 'LmsLevel', :foreign_key => :difficulty_id, optional: true
    belongs_to :news_article, :class_name => 'NewsArticle', :foreign_key => :article_id, optional: true

    has_many :news_article_sections, through: :news_article,:class_name => 'NewsArticleSection', :foreign_key => :article_id	

    validates :name, presence: true
    validates :introduction, presence: true
    validates :reward, presence: true

	manage_with_tolaria using: {
	    icon: "file-o",
	    category: "Lms",
	    priority: 1,
	    permit_params: [
	    	:name,
	      	:introduction,
	      	:public,
	      	:reward,
	      	:time,
	      	:published,
	      	:created_by_id,
	      	:difficulty_id,
	      	:course_id,
	      	:article_id,
	      	:private_content,
			:lms_word_ids => [],
			:latamusers_intitution_ids => []
	    ]
	}

end

app/views/admin/lms_activities/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>

<% user = AuthUser.find(current_administrator.auth_user_id)%>
<% if user.auth_permissions.where('"auth_permission"."codename" = ? OR "auth_permission"."codename" = ?', "add_activity", "change_activity").present? || user.is_superuser == true %>

<%= f.label :name %>
<%= f.text_field :name , placeholder:"Name of the activity" %>
<%= f.hint "Please type the name of the activity" %>
<br><br><br><br><br>	

<%= f.label :introduction %><br><br><br>
<%= f.cktext_area :introduction %>
<%= f.hint "Please add an introduction for the activity" %>

<%= f.label :created_by_id, "Author" %>
<%= f.searchable_select :created_by_id, AuthUser.all, :id, :username, include_blank:false %>
<%= f.hint "Select the person who wrote this post." %>

<%= f.label :lms_word_ids, "Words" %>
<div class="field-cluster"><%= f.searchable_select :lms_word_ids, LmsWord.order(word: :asc), :id, :word_with_use, multiple:true %><button class="button" id="refresh-words"><%= image_tag("refresh.jpg", size: "30x30")%></button></div>
<%= f.hint "Select each word that applies to this activity" %>

<%= f.label :difficulty_id, "Level" %>
<%= f.searchable_select :difficulty_id, LmsLevel.all.order(:difficulty_level), :id, :difficulty_level, include_blank:false %>
<%= f.hint "Select the level of the activity." %>

<%= f.label :course_id %>
<%= f.searchable_select :course_id, LmsCourse.all, :id, :name %>
<%= f.hint "Select the course tha applies to this activity" %>

<%= f.label :article_id %>
<div class="field-cluster"><%= f.searchable_select :article_id, NewsArticle.order(id: :desc), :id, :title %><button class="button" id="refresh-articles"><%= image_tag("refresh.jpg", size: "30x30")%></button></div>
<%= f.hint "Select the article tha applies to this activity" %>

<%= f.label :reward %>
<%= f.text_field :reward , placeholder:"Reward", type: "number"%>
<%= f.hint "Number of the reward" %>

<%= f.label :time %>
<%= f.text_field :time , placeholder:"Time", type: "number"%>
<%= f.hint "Number of minutes user has to complete the activity" %>

<%= f.label :published, "Published" %>
<div class="field-cluster"><%= f.check_box :published %><span style="color: red;">Obligatory if you want to show in the list of activities or articles</span></div>
<%= f.hint "Select if the activity is published" %>

<%= f.label :public, "Public" %>
<div class="field-cluster"><%= f.check_box :public %></div>
<%= f.hint "Select if the activity is public" %>

<%= f.label :private_content, "Private content" %>
<div class="field-cluster"><%= f.check_box :private_content %></div>
<%= f.hint "Select if the content is private for the institution" %>

<%= f.label :latamusers_intitution_ids, "Institutions" %>
<%= f.searchable_select :latamusers_intitution_ids, LatamusersIntitution.all, :id, :name, multiple:true %>
<%= f.hint "Select each word that applies to this activity" %>

<% else %>
  No tienes los permisos necesarios para modificar la página
<% end %>

<script type="text/javascript">

	(function(funcName, baseObj) {
	    funcName = funcName || "docReady";
	    baseObj = baseObj || window;
	    var readyList = [];
	    var readyFired = false;
	    var readyEventHandlersInstalled = false;

	    function ready() {
	        if (!readyFired) {
	            readyFired = true;
	            for (var i = 0; i < readyList.length; i++) {
	                readyList[i].fn.call(window, readyList[i].ctx);
	            }
	            readyList = [];
	        }
	    }

	    function readyStateChange() {
	        if ( document.readyState === "complete" ) {
	            ready();
	        }
	    }

	    baseObj[funcName] = function(callback, context) {
	        if (typeof callback !== "function") {
	            throw new TypeError("callback for docReady(fn) must be a function");
	        }
	        if (readyFired) {
	            setTimeout(function() {callback(context);}, 1);
	            return;
	        } else {
	            readyList.push({fn: callback, ctx: context});
	        }
	        if (document.readyState === "complete") {
	            setTimeout(ready, 1);
	        } else if (!readyEventHandlersInstalled) {
	            if (document.addEventListener) {
	                document.addEventListener("DOMContentLoaded", ready, false);
	                window.addEventListener("load", ready, false);
	            } else {
	                document.attachEvent("onreadystatechange", readyStateChange);
	                window.attachEvent("onload", ready);
	            }
	            readyEventHandlersInstalled = true;
	        }
	    }
	})("docReady", window);

	docReady(function() {
		$("#refresh-words").click(function reload_words(){
			html_select = "";
			html_selected = [];
			$("#lms_activity_lms_word_ids_chosen .chosen-choices .search-choice .search-choice-close").each(function(i, obj) {
				html_selected.push($('#lms_activity_lms_word_ids option').eq($(this).attr("data-option-array-index")).val());
			});
			$.ajax({
				url : '/get_words',
				type : 'POST',
				dataType : 'json',
				beforeSend: function() {
					$("#refresh-words").html('<%= image_tag("refresh.gif", size: "30x30")%>');
					$("#refresh-words").prop("disabled", true);
				},
				success : function(json) {
					for(i = 0; i < json.length; i++){
						object = json[i];
						html_select = html_select + '<option value="'+object["id"]+'">'+object["word"]+' - '+object["use"]+'</option>';
					}
					$('#lms_activity_lms_word_ids').html(html_select);
					$("#lms_activity_lms_word_ids").val(html_selected).trigger('chosen:updated');
				},
				error : function(xhr, status) {
				    alert("Error al obtener de nuevo las palabras, intenta de nuevo");
				},
				complete : function(xhr, status) {
				    $("#refresh-words").html('<%= image_tag("refresh.jpg", size: "30x30")%>');
				    $("#refresh-words").prop("disabled", false);
				}
			});
		});

		$("#refresh-articles").click(function reload_articles(){
			html_select = "";
			html_selected = $('#lms_activity_article_id').val();
			$.ajax({
				url : '/get_articles',
				type : 'POST',
				dataType : 'json',
				beforeSend: function() {
					$("#refresh-articles").html('<%= image_tag("refresh.gif", size: "30x30")%>');
					$("#refresh-articles").prop("disabled", true);
				},
				success : function(json) {
					for(i = 0; i < json.length; i++){
						object = json[i];
						html_select = html_select + '<option value="'+object["id"]+'">'+object["title"]+'</option>';
					}
					$('#lms_activity_article_id').html(html_select);
					$("#lms_activity_article_id").val(html_selected).trigger('chosen:updated');
				},
				error : function(xhr, status) {
				    alert("Error al obtener de nuevo los artículos, intenta de nuevo");
				},
				complete : function(xhr, status) {
				    $("#refresh-articles").html('<%= image_tag("refresh.jpg", size: "30x30")%>');
				    $("#refresh-articles").prop("disabled", false);
				}
			});
		});
	});

</script>

<script type="text/javascript">
	CKEDITOR.config.pasteFromWordRemoveStyles = true;
</script>

app/views/admin/lms_activities/_index.html.erb
<% user = AuthUser.find(current_administrator.auth_user_id)%>
<% if user.auth_permissions.where('"auth_permission"."codename" = ?', "delete_activity").present? || user.is_superuser == true %>

<%= index_table do %>
  <thead>
    <tr>
      <%= index_th :name %>
      <%= index_th :preview %>
      <%= actions_th %>
    </tr>
  </thead>
  <tbody>
    <% @resources.each do |obj| %>
      <tr>
        <%= index_td obj, obj.name %>
        <td class="actions-td"><%= link_to "Go to preview", preview_path(:id => obj.id), target: :"blank", class: "button -small -edit" %></td>
        <%= actions_td obj %>
      </tr>
    <% end %>
  </tbody>
<% end %>

<% else %>
  No tienes los permisos necesarios para modificar la página
<% end %>